version: '3.6'

# 视频流服务器
services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
    container_name: srs
    restart: always
    hostname: "srs"
    ports:
      - 11935:1935
      - 11985:1985
      - 18080:8080
    networks:
      - srs

networks:
  srs:
    driver: bridge

# 推送视频流 客户端
# docker run --rm -it ossrs/srs:encoder ffmpeg -stream_loop -1 -re -i doc/source.flv -c copy -f flv rtmp://192.168.50.47:11935/live/livestream

# 推送地址
# rtmp://192.168.50.47:11935/live/livestream
# 观看地址
# http://192.168.50.47:11935/live/livestream.flv
# http://192.168.50.47:18080/live/livestream.m3u8

# 可以多路推送，修改对象的推送地址和观看地址
# 如：rtmp://192.168.50.47:11935/live/livestream/01
# http://192.168.50.47:11935/live/livestream/01.flv
# http://192.168.50.47:11935/live/livestream/01.m3u8